import type { Metadata } from 'next'

import PageFullNavHeader from '@/components/Headers/PageFullNavHeader';
import PrimaryFooter from '@/components/PrimaryFooter';
import { builder } from '@builder.io/sdk';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

builder.init(process.env.NEXT_PUBLIC_BUILDER_API_KEY as string);

export default async function RootLayout({
  children,
  params,
  pageCondensedNav,
  pageFullNav,
}: {
  children: React.ReactNode;
  pageCondensedNav: React.ReactNode;
  pageFullNav: React.ReactNode;
  params: { page: string[] }
}) {
  const urlPath = "/" + ((params?.page as string[])?.join("/") || "")

  const pageModelUrls = await builder
    .getAll("page", {
      fields: 'data.url',
      options: { noTargeting: true },
    })
  const pageFullNavModelUrls = await builder
    .getAll("page-full-nav", {
      fields: 'data.url',
      options: { noTargeting: true },
    })

  if (pageModelUrls.map(page => page?.data?.url).includes(urlPath)) {
    return <>{pageCondensedNav}</>
  }

  if (pageFullNavModelUrls.map(page => page?.data?.url).includes(urlPath)) {
    return <>{pageFullNav}</>
  }

  return <>{children}</>
}
