import type { Metadata } from 'next'

import PageFullNavHeader from '@/components/Headers/PageFullNavHeader';
import PrimaryFooter from '@/components/PrimaryFooter';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { page: string[] }
}) {
  return (
    <>
      <PageFullNavHeader />

      <main>
        {children}
      </main>

      <footer>
        <PrimaryFooter params={{
          urlPath: params?.page
        }} />
      </footer>
    </>
  )
}
