import type { Metadata } from 'next'
import { builder } from "@builder.io/sdk";

import "@/styles/globals.css"

builder.init(process.env.NEXT_PUBLIC_BUILDER_API_KEY as string);

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
