import type { Metadata } from 'next'

import PageFullNavHeader from '@/components/Headers/PageFullNavHeader';

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PageFullNavHeader />

        <main style={{ height: 10000 }}>
          {children}
        </main>

        <footer>

        </footer>
      </body>
    </html>
  )
}
