import type { Metadata } from 'next'
import Link from 'next/link';

import PageFullNavHeader from '@/components/Headers/PageFullNavHeader';
import PrimaryFooter from '@/components/PrimaryFooter';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
